### PR TITLE
Performed more edits in new "proofreading" branch

### PR DESCRIPTION
**Pull request by tommytwoeyes**
Hi Robin,

I performed some more editing today, to the file manuscript/chapter3.md.

### CODE REVIEW

**Review by tommytwoeyes — COMMENTED** [review]
Commit msg should say, "Replaced 'sign up page' -> 'sign-up page'"

**Review by tommytwoeyes — COMMENTED** [review]
Commit msg should say, "Replaced 'sign up page' -> 'sign-up page'"

**Review by tommytwoeyes — COMMENTED** [review]
Commit msg should say, "Replaced 'sign up page' -> 'sign-up page'"

**Comment by rwieruch** [comment]
Perfect @tommytwoeyes  💯 Thank you so much. This helps a lot to give other people a better reading experience :)

**Pull request merged**
